language: java

jdk:
  - oraclejdk7

env:
  - PATH=$PATH:/tmp/sonar-runner-2.4/bin RAILS_ENV=production

install:
  - cd /tmp
  - wget -O sonarqube.zip http://downloads.sonarsource.com/sonarqube/sonarqube-5.1.1.zip
  - unzip sonarqube.zip
  - ./sonarqube-5.1.1/bin/linux-x86-64/sonar.sh start
  - wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
  - unzip sonar-runner-dist-2.4.zip
  - cd -

script:
  - ./gradlew clean build integTest

before_install:
 - chmod +x gradlew