sudo: required

language: java

services: docker

jdk: oraclejdk8

env:
  matrix:
    - SONARQUBE_VERSION=5.6.6 PATH=/tmp/sonar-scanner-2.5/bin:$PATH
    - SONARQUBE_VERSION=6.0 PATH=/tmp/sonar-scanner-2.5/bin:$PATH
    - SONARQUBE_VERSION=6.1 PATH=/tmp/sonar-scanner-2.5/bin:$PATH
    - SONARQUBE_VERSION=6.2 PATH=/tmp/sonar-scanner-2.5/bin:$PATH
    - SONARQUBE_VERSION=6.3 PATH=/tmp/sonar-scanner-2.5/bin:$PATH

install:
  - cd /tmp
  - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.5.zip
  - unzip sonar-scanner-2.5.zip
  - cd -
  - docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube:${SONARQUBE_VERSION}

script:
  - ./gradlew clean build integTest

before_install:
 - chmod +x gradlew
